---
kind: pipeline
name: default

steps:
- name: copy-sigs
  image: alpine:3
  commands:
  - cp /tmp/signatures.json site/data/signatures/signatures.json
  volumes:
  - name: signatures
    path: /tmp/signatures.json

- name: hugo
  image: plugins/hugo
  settings:
    source: site
    validate: true

- name: deploy
  image: docker/compose:1.29.1
  commands:
  - docker-compose -p pmpc-website up --build -d
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    branch:
    - master
    event:
    - push
    - tag
    - deployment
    - cron

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: signatures
  host:
    path: /srv/forms/pmpc/signatures.json

...
