---
# SPDX-FileCopyrightText: 2017 Free Software Foundation Europe e.V. <https://fsfe.org>
# 
# SPDX-License-Identifier: GPL-3.0-or-later

kind: pipeline
name: default

steps:
  - name: copy-sigs
    image: alpine:3
    commands:
      - cp /tmp/signatures.json site/assets/signatures/signatures.json
    volumes:
      - name: signatures
        path: /tmp/signatures.json
    when:
      branch:
        - master
      event:
        exclude:
          # do not copy sigs in pull requests to speed up builds
          - pull_request

  - name: deploy
    image: docker:20
    environment:
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
    commands:
      - docker compose -p pmpc-website up --build -d
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    when:
      branch:
        - master
      event:
        - push
        - tag
        - deployment
        - cron

# This has to run on the same machine as the forms API until this feature
# exists: https://git.fsfe.org/fsfe-system-hackers/forms/issues/62
node:
  cont2: noris

volumes:
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
  - name: signatures
    host:
      path: /srv/forms/pmpc/signatures.json
---
kind: signature
hmac: 459b9bf35c6d37739f245e9fc2af354e5efcbc1bb0bdbff4c1c7b38c89ca3c6f

...
