version: "3"
services:
  pmpc:
    container_name: pmpc
    build: .
    image: pmpc
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"
    ports:
      - "50:8080"
    labels:
      proxy.host: "publiccode.eu"
      proxy.host_alias: "www.publiccode.eu"
      proxy.port: "50"
