# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: CC0-1.0

services:
  mep-image-fetcher:
    container_name: mep-image-fetcher
    build:
      context: .
      dockerfile: ./mep-image-fetcher/Dockerfile
    image: mep-image-fetcher
    volumes:
      - pmpc-website-mep-pics:/mep-image-fetcher/meps
  pmpc:
    container_name: pmpc
    build:
      context: .
      args:
        - HUGO_DIR=/src/site
    image: pmpc
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"
    # Reverse proxy
    labels:
      proxy.host: "publiccode.eu"
      proxy.host_alias: "www.publiccode.eu"
      proxy.port: "9260"
    ports:
      - "9260:8043"
    volumes:
      - pmpc-website-mep-pics:/srv/http/img/meps
volumes:
  pmpc-website-mep-pics:
