# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  pmpc:
    container_name: pmpc
    build:
      context: site
    image: pmpc
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"
    # Reverse proxy
    labels:
      proxy.host: "publiccode.eu"
      proxy.host_alias: "www.publiccode.eu"
      proxy.port: "9260"
    ports:
      - "9260:8043"
